/** @type {import('tailwindcss').Config} */
module.exports = {
	// NOTE: Update this to include the paths to all of your component files.
	content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
	safelist: [
		"dark",
		"blue",
		"green",
		"violet",
		"zinc",
		"black",
		"dark:blue",
		"dark:green",
		"dark:violet",
		"dark:zinc",
		"dark:black",
		"dark.violet",
		"dark.green",
		"dark.zinc",
		"dark.black",
		"dark.blue",
		"mono",
		"claude",
		"vercel",
		"twitter",
		"supabase",
		"dark.mono",
		"dark.claude",
		"dark.vercel",
		"dark.twitter",
		"dark.supabase",
		"monodark",
		"claudedark",
		"verceldark",
		"twitterdark",
		"supabasedark",
	],
	darkMode: "class",
	presets: [require("nativewind/preset")],
	theme: {
		extend: {
			colors: {
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			fontFamily: {
				// sans: [
				// 	"system-ui",
				// 	"-apple-system",
				// 	"BlinkMacSystemFont",
				// 	'"Segoe UI"',
				// 	"Roboto",
				// 	"Helvetica",
				// 	"Arial",
				// 	"sans-serif",
				// ],
				sans: ["Geist_400Regular"],
				geist: ["Geist_400Regular"],
				"geist-thin": ["Geist_100Thin"],
				"geist-light": ["Geist_300Light"],
				"geist-medium": ["Geist_500Medium"],
				"geist-semibold": ["Geist_600SemiBold"],
				"geist-bold": ["Geist_700Bold"],
				"geist-black": ["Geist_900Black"],
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
